# Each command should be a separate item in the list
# Also don't include the slash at the start
# Simply remove commands and comment out an item to disable commands, like AFKAction is by default
AFKStart:
  - "say AFKStart"
  - "say anther command"
AFKStop:
  - "say AFKStop"
#AFKAction:
#  - "say AFKAction"